---
apiVersion: v1
kind: Namespace
metadata:
  name: autoscale

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
  namespace: autoscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-server
  template:
    metadata:
      labels:
        app: apache-server
    spec:
      containers:
      - name: apache-server
        image: httpd:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m      # REQUIRED for HPA to work!
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: apache-server
  namespace: autoscale
spec:
  selector:
    app: apache-server
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
